replicaCount: 2

image:
  repository: my-dockerhub-user/catalog
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
