replicaCount: 2

image:
  repository: my-dockerhub-user/ui
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: NODE_ENV
    value: "production"

serviceMonitor:
  enabled: true
  path: /metrics
